<?php
/**
 * Customer
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tid\CustomaPHP\Model;

use \ArrayAccess;
use \Tid\CustomaPHP\ObjectSerializer;

/**
 * Customer Class Doc Comment
 *
 * @category Class
 * @description Customer object containing all customer data.
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Customer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Customer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'creation_date' => '\DateTime',
        'modification_date' => '\DateTime',
        'id' => 'string',
        'number' => 'string',
        'group' => 'string',
        'salutation' => 'string',
        'title' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'company' => 'string',
        'address' => 'string',
        'postal_code' => 'string',
        'suburb' => 'string',
        'city' => 'string',
        'country' => 'string',
        'e_mail' => 'string',
        'phone' => 'string',
        'birthday' => '\DateTime',
        'referrer' => 'string',
        'referrer_channel' => 'string',
        'register_date' => '\DateTime',
        'purchase_date' => '\DateTime',
        'additional_fields' => '\Tid\CustomaPHP\Model\AdditionalField[]',
        'reference_customer' => 'bool',
        'contact_ban' => 'bool',
        'external_customer_id' => 'int',
        'external_customer_external_id' => 'string',
        'external_order_type' => 'string',
        'external_order_account_id' => 'int',
        'external_order_sub_account_id' => 'string',
        'marketplace' => 'string',
        'test_user' => 'bool',
        'newsletter' => 'bool',
        'segment' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'creation_date' => 'date-time',
        'modification_date' => 'date-time',
        'id' => null,
        'number' => null,
        'group' => null,
        'salutation' => null,
        'title' => null,
        'first_name' => null,
        'last_name' => null,
        'company' => null,
        'address' => null,
        'postal_code' => null,
        'suburb' => null,
        'city' => null,
        'country' => null,
        'e_mail' => 'email',
        'phone' => null,
        'birthday' => 'date',
        'referrer' => null,
        'referrer_channel' => null,
        'register_date' => 'date-time',
        'purchase_date' => 'date-time',
        'additional_fields' => null,
        'reference_customer' => null,
        'contact_ban' => null,
        'external_customer_id' => null,
        'external_customer_external_id' => null,
        'external_order_type' => null,
        'external_order_account_id' => null,
        'external_order_sub_account_id' => null,
        'marketplace' => null,
        'test_user' => null,
        'newsletter' => null,
        'segment' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'creation_date' => false,
        'modification_date' => false,
        'id' => false,
        'number' => false,
        'group' => true,
        'salutation' => false,
        'title' => false,
        'first_name' => false,
        'last_name' => false,
        'company' => false,
        'address' => false,
        'postal_code' => false,
        'suburb' => false,
        'city' => false,
        'country' => false,
        'e_mail' => false,
        'phone' => false,
        'birthday' => true,
        'referrer' => false,
        'referrer_channel' => false,
        'register_date' => false,
        'purchase_date' => true,
        'additional_fields' => false,
        'reference_customer' => false,
        'contact_ban' => false,
        'external_customer_id' => false,
        'external_customer_external_id' => true,
        'external_order_type' => false,
        'external_order_account_id' => false,
        'external_order_sub_account_id' => false,
        'marketplace' => false,
        'test_user' => false,
        'newsletter' => false,
        'segment' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'creation_date' => 'CreationDate',
        'modification_date' => 'ModificationDate',
        'id' => 'ID',
        'number' => 'Number',
        'group' => 'Group',
        'salutation' => 'Salutation',
        'title' => 'Title',
        'first_name' => 'FirstName',
        'last_name' => 'LastName',
        'company' => 'Company',
        'address' => 'Address',
        'postal_code' => 'PostalCode',
        'suburb' => 'Suburb',
        'city' => 'City',
        'country' => 'Country',
        'e_mail' => 'EMail',
        'phone' => 'Phone',
        'birthday' => 'Birthday',
        'referrer' => 'Referrer',
        'referrer_channel' => 'ReferrerChannel',
        'register_date' => 'RegisterDate',
        'purchase_date' => 'PurchaseDate',
        'additional_fields' => 'AdditionalFields',
        'reference_customer' => 'ReferenceCustomer',
        'contact_ban' => 'ContactBan',
        'external_customer_id' => 'ExternalCustomerID',
        'external_customer_external_id' => 'ExternalCustomerExternalID',
        'external_order_type' => 'ExternalOrderType',
        'external_order_account_id' => 'ExternalOrderAccountID',
        'external_order_sub_account_id' => 'ExternalOrderSubAccountID',
        'marketplace' => 'Marketplace',
        'test_user' => 'TestUser',
        'newsletter' => 'Newsletter',
        'segment' => 'Segment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'creation_date' => 'setCreationDate',
        'modification_date' => 'setModificationDate',
        'id' => 'setId',
        'number' => 'setNumber',
        'group' => 'setGroup',
        'salutation' => 'setSalutation',
        'title' => 'setTitle',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'company' => 'setCompany',
        'address' => 'setAddress',
        'postal_code' => 'setPostalCode',
        'suburb' => 'setSuburb',
        'city' => 'setCity',
        'country' => 'setCountry',
        'e_mail' => 'setEMail',
        'phone' => 'setPhone',
        'birthday' => 'setBirthday',
        'referrer' => 'setReferrer',
        'referrer_channel' => 'setReferrerChannel',
        'register_date' => 'setRegisterDate',
        'purchase_date' => 'setPurchaseDate',
        'additional_fields' => 'setAdditionalFields',
        'reference_customer' => 'setReferenceCustomer',
        'contact_ban' => 'setContactBan',
        'external_customer_id' => 'setExternalCustomerId',
        'external_customer_external_id' => 'setExternalCustomerExternalId',
        'external_order_type' => 'setExternalOrderType',
        'external_order_account_id' => 'setExternalOrderAccountId',
        'external_order_sub_account_id' => 'setExternalOrderSubAccountId',
        'marketplace' => 'setMarketplace',
        'test_user' => 'setTestUser',
        'newsletter' => 'setNewsletter',
        'segment' => 'setSegment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'creation_date' => 'getCreationDate',
        'modification_date' => 'getModificationDate',
        'id' => 'getId',
        'number' => 'getNumber',
        'group' => 'getGroup',
        'salutation' => 'getSalutation',
        'title' => 'getTitle',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'company' => 'getCompany',
        'address' => 'getAddress',
        'postal_code' => 'getPostalCode',
        'suburb' => 'getSuburb',
        'city' => 'getCity',
        'country' => 'getCountry',
        'e_mail' => 'getEMail',
        'phone' => 'getPhone',
        'birthday' => 'getBirthday',
        'referrer' => 'getReferrer',
        'referrer_channel' => 'getReferrerChannel',
        'register_date' => 'getRegisterDate',
        'purchase_date' => 'getPurchaseDate',
        'additional_fields' => 'getAdditionalFields',
        'reference_customer' => 'getReferenceCustomer',
        'contact_ban' => 'getContactBan',
        'external_customer_id' => 'getExternalCustomerId',
        'external_customer_external_id' => 'getExternalCustomerExternalId',
        'external_order_type' => 'getExternalOrderType',
        'external_order_account_id' => 'getExternalOrderAccountId',
        'external_order_sub_account_id' => 'getExternalOrderSubAccountId',
        'marketplace' => 'getMarketplace',
        'test_user' => 'getTestUser',
        'newsletter' => 'getNewsletter',
        'segment' => 'getSegment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SALUTATION_M = 'm';
    public const SALUTATION_F = 'f';
    public const SALUTATION_X = 'x';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSalutationAllowableValues()
    {
        return [
            self::SALUTATION_M,
            self::SALUTATION_F,
            self::SALUTATION_X,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('modification_date', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
        $this->setIfExists('salutation', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('company', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('postal_code', $data ?? [], null);
        $this->setIfExists('suburb', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('e_mail', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('birthday', $data ?? [], null);
        $this->setIfExists('referrer', $data ?? [], null);
        $this->setIfExists('referrer_channel', $data ?? [], null);
        $this->setIfExists('register_date', $data ?? [], null);
        $this->setIfExists('purchase_date', $data ?? [], null);
        $this->setIfExists('additional_fields', $data ?? [], null);
        $this->setIfExists('reference_customer', $data ?? [], null);
        $this->setIfExists('contact_ban', $data ?? [], null);
        $this->setIfExists('external_customer_id', $data ?? [], null);
        $this->setIfExists('external_customer_external_id', $data ?? [], null);
        $this->setIfExists('external_order_type', $data ?? [], null);
        $this->setIfExists('external_order_account_id', $data ?? [], null);
        $this->setIfExists('external_order_sub_account_id', $data ?? [], null);
        $this->setIfExists('marketplace', $data ?? [], null);
        $this->setIfExists('test_user', $data ?? [], null);
        $this->setIfExists('newsletter', $data ?? [], null);
        $this->setIfExists('segment', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['number']) && (mb_strlen($this->container['number']) > 32)) {
            $invalidProperties[] = "invalid value for 'number', the character length must be smaller than or equal to 32.";
        }

        if (!is_null($this->container['group']) && (mb_strlen($this->container['group']) > 255)) {
            $invalidProperties[] = "invalid value for 'group', the character length must be smaller than or equal to 255.";
        }

        $allowedValues = $this->getSalutationAllowableValues();
        if (!is_null($this->container['salutation']) && !in_array($this->container['salutation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'salutation', must be one of '%s'",
                $this->container['salutation'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['title']) && (mb_strlen($this->container['title']) > 30)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['first_name']) && (mb_strlen($this->container['first_name']) > 256)) {
            $invalidProperties[] = "invalid value for 'first_name', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['last_name']) && (mb_strlen($this->container['last_name']) > 256)) {
            $invalidProperties[] = "invalid value for 'last_name', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['company']) && (mb_strlen($this->container['company']) > 256)) {
            $invalidProperties[] = "invalid value for 'company', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['address']) && (mb_strlen($this->container['address']) > 256)) {
            $invalidProperties[] = "invalid value for 'address', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['postal_code']) && (mb_strlen($this->container['postal_code']) > 16)) {
            $invalidProperties[] = "invalid value for 'postal_code', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['suburb']) && (mb_strlen($this->container['suburb']) > 256)) {
            $invalidProperties[] = "invalid value for 'suburb', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['city']) && (mb_strlen($this->container['city']) > 256)) {
            $invalidProperties[] = "invalid value for 'city', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['country']) && (mb_strlen($this->container['country']) > 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['e_mail']) && (mb_strlen($this->container['e_mail']) > 128)) {
            $invalidProperties[] = "invalid value for 'e_mail', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['phone']) && (mb_strlen($this->container['phone']) > 256)) {
            $invalidProperties[] = "invalid value for 'phone', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['referrer']) && (mb_strlen($this->container['referrer']) > 256)) {
            $invalidProperties[] = "invalid value for 'referrer', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['referrer_channel']) && (mb_strlen($this->container['referrer_channel']) > 32)) {
            $invalidProperties[] = "invalid value for 'referrer_channel', the character length must be smaller than or equal to 32.";
        }

        if (!is_null($this->container['external_customer_external_id']) && (mb_strlen($this->container['external_customer_external_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'external_customer_external_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['external_order_type']) && (mb_strlen($this->container['external_order_type']) > 20)) {
            $invalidProperties[] = "invalid value for 'external_order_type', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['external_order_sub_account_id']) && (mb_strlen($this->container['external_order_sub_account_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'external_order_sub_account_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['marketplace']) && (mb_strlen($this->container['marketplace']) > 64)) {
            $invalidProperties[] = "invalid value for 'marketplace', the character length must be smaller than or equal to 64.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets creation_date
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime|null $creation_date Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets modification_date
     *
     * @return \DateTime|null
     */
    public function getModificationDate()
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     *
     * @param \DateTime|null $modification_date Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setModificationDate($modification_date)
    {
        if (is_null($modification_date)) {
            throw new \InvalidArgumentException('non-nullable modification_date cannot be null');
        }
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID of the customer. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string|null $number Customer number from e.g. an external Shop or ERP System.
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        if ((mb_strlen($number) > 32)) {
            throw new \InvalidArgumentException('invalid length for $number when calling Customer., must be smaller than or equal to 32.');
        }

        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets group
     *
     * @return string|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param string|null $group Group name of the customer
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            array_push($this->openAPINullablesSetToNull, 'group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($group) && (mb_strlen($group) > 255)) {
            throw new \InvalidArgumentException('invalid length for $group when calling Customer., must be smaller than or equal to 255.');
        }

        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets salutation
     *
     * @return string|null
     */
    public function getSalutation()
    {
        return $this->container['salutation'];
    }

    /**
     * Sets salutation
     *
     * @param string|null $salutation Salutation of the customer. 'm' for male, 'f' for female and 'x' for neither or unknown.
     *
     * @return self
     */
    public function setSalutation($salutation)
    {
        if (is_null($salutation)) {
            throw new \InvalidArgumentException('non-nullable salutation cannot be null');
        }
        $allowedValues = $this->getSalutationAllowableValues();
        if (!in_array($salutation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'salutation', must be one of '%s'",
                    $salutation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['salutation'] = $salutation;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title (Academical) title of the customer.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        if ((mb_strlen($title) > 30)) {
            throw new \InvalidArgumentException('invalid length for $title when calling Customer., must be smaller than or equal to 30.');
        }

        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name First name of the customer.
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        if ((mb_strlen($first_name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $first_name when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name Last name of the customer.
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        if ((mb_strlen($last_name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $last_name when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets company
     *
     * @return string|null
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param string|null $company Company of the customer's address
     *
     * @return self
     */
    public function setCompany($company)
    {
        if (is_null($company)) {
            throw new \InvalidArgumentException('non-nullable company cannot be null');
        }
        if ((mb_strlen($company) > 256)) {
            throw new \InvalidArgumentException('invalid length for $company when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address (Street) address of the customer
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        if ((mb_strlen($address) > 256)) {
            throw new \InvalidArgumentException('invalid length for $address when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string|null $postal_code Postal code of the customer's address
     *
     * @return self
     */
    public function setPostalCode($postal_code)
    {
        if (is_null($postal_code)) {
            throw new \InvalidArgumentException('non-nullable postal_code cannot be null');
        }
        if ((mb_strlen($postal_code) > 16)) {
            throw new \InvalidArgumentException('invalid length for $postal_code when calling Customer., must be smaller than or equal to 16.');
        }

        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets suburb
     *
     * @return string|null
     */
    public function getSuburb()
    {
        return $this->container['suburb'];
    }

    /**
     * Sets suburb
     *
     * @param string|null $suburb Suburb of the customer's address
     *
     * @return self
     */
    public function setSuburb($suburb)
    {
        if (is_null($suburb)) {
            throw new \InvalidArgumentException('non-nullable suburb cannot be null');
        }
        if ((mb_strlen($suburb) > 256)) {
            throw new \InvalidArgumentException('invalid length for $suburb when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['suburb'] = $suburb;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city City of the customer's address
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        if ((mb_strlen($city) > 256)) {
            throw new \InvalidArgumentException('invalid length for $city when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country ISO3166-1 Alpha-2 Code of the customer's country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        if ((mb_strlen($country) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling Customer., must be smaller than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets e_mail
     *
     * @return string|null
     */
    public function getEMail()
    {
        return $this->container['e_mail'];
    }

    /**
     * Sets e_mail
     *
     * @param string|null $e_mail Email address of the customer.
     *
     * @return self
     */
    public function setEMail($e_mail)
    {
        if (is_null($e_mail)) {
            throw new \InvalidArgumentException('non-nullable e_mail cannot be null');
        }
        if ((mb_strlen($e_mail) > 128)) {
            throw new \InvalidArgumentException('invalid length for $e_mail when calling Customer., must be smaller than or equal to 128.');
        }

        $this->container['e_mail'] = $e_mail;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Phone number of the customer.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        if ((mb_strlen($phone) > 256)) {
            throw new \InvalidArgumentException('invalid length for $phone when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets birthday
     *
     * @return \DateTime|null
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param \DateTime|null $birthday Date of birth of the customer.
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        if (is_null($birthday)) {
            array_push($this->openAPINullablesSetToNull, 'birthday');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthday', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthday'] = $birthday;

        return $this;
    }

    /**
     * Gets referrer
     *
     * @return string|null
     */
    public function getReferrer()
    {
        return $this->container['referrer'];
    }

    /**
     * Sets referrer
     *
     * @param string|null $referrer Referrer (last cookie) of the customer.
     *
     * @return self
     */
    public function setReferrer($referrer)
    {
        if (is_null($referrer)) {
            throw new \InvalidArgumentException('non-nullable referrer cannot be null');
        }
        if ((mb_strlen($referrer) > 256)) {
            throw new \InvalidArgumentException('invalid length for $referrer when calling Customer., must be smaller than or equal to 256.');
        }

        $this->container['referrer'] = $referrer;

        return $this;
    }

    /**
     * Gets referrer_channel
     *
     * @return string|null
     */
    public function getReferrerChannel()
    {
        return $this->container['referrer_channel'];
    }

    /**
     * Sets referrer_channel
     *
     * @param string|null $referrer_channel Referrer Channel of the customer.
     *
     * @return self
     */
    public function setReferrerChannel($referrer_channel)
    {
        if (is_null($referrer_channel)) {
            throw new \InvalidArgumentException('non-nullable referrer_channel cannot be null');
        }
        if ((mb_strlen($referrer_channel) > 32)) {
            throw new \InvalidArgumentException('invalid length for $referrer_channel when calling Customer., must be smaller than or equal to 32.');
        }

        $this->container['referrer_channel'] = $referrer_channel;

        return $this;
    }

    /**
     * Gets register_date
     *
     * @return \DateTime|null
     */
    public function getRegisterDate()
    {
        return $this->container['register_date'];
    }

    /**
     * Sets register_date
     *
     * @param \DateTime|null $register_date Registration date of the customer.
     *
     * @return self
     */
    public function setRegisterDate($register_date)
    {
        if (is_null($register_date)) {
            throw new \InvalidArgumentException('non-nullable register_date cannot be null');
        }
        $this->container['register_date'] = $register_date;

        return $this;
    }

    /**
     * Gets purchase_date
     *
     * @return \DateTime|null
     */
    public function getPurchaseDate()
    {
        return $this->container['purchase_date'];
    }

    /**
     * Sets purchase_date
     *
     * @param \DateTime|null $purchase_date Purchase date of the customer.
     *
     * @return self
     */
    public function setPurchaseDate($purchase_date)
    {
        if (is_null($purchase_date)) {
            array_push($this->openAPINullablesSetToNull, 'purchase_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('purchase_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['purchase_date'] = $purchase_date;

        return $this;
    }

    /**
     * Gets additional_fields
     *
     * @return \Tid\CustomaPHP\Model\AdditionalField[]|null
     */
    public function getAdditionalFields()
    {
        return $this->container['additional_fields'];
    }

    /**
     * Sets additional_fields
     *
     * @param \Tid\CustomaPHP\Model\AdditionalField[]|null $additional_fields Additional data for the customer.
     *
     * @return self
     */
    public function setAdditionalFields($additional_fields)
    {
        if (is_null($additional_fields)) {
            throw new \InvalidArgumentException('non-nullable additional_fields cannot be null');
        }
        $this->container['additional_fields'] = $additional_fields;

        return $this;
    }

    /**
     * Gets reference_customer
     *
     * @return bool|null
     */
    public function getReferenceCustomer()
    {
        return $this->container['reference_customer'];
    }

    /**
     * Sets reference_customer
     *
     * @param bool|null $reference_customer Determines if the customer is a reference customer.
     *
     * @return self
     */
    public function setReferenceCustomer($reference_customer)
    {
        if (is_null($reference_customer)) {
            throw new \InvalidArgumentException('non-nullable reference_customer cannot be null');
        }
        $this->container['reference_customer'] = $reference_customer;

        return $this;
    }

    /**
     * Gets contact_ban
     *
     * @return bool|null
     */
    public function getContactBan()
    {
        return $this->container['contact_ban'];
    }

    /**
     * Sets contact_ban
     *
     * @param bool|null $contact_ban Determines if the customer has an active contact ban.
     *
     * @return self
     */
    public function setContactBan($contact_ban)
    {
        if (is_null($contact_ban)) {
            throw new \InvalidArgumentException('non-nullable contact_ban cannot be null');
        }
        $this->container['contact_ban'] = $contact_ban;

        return $this;
    }

    /**
     * Gets external_customer_id
     *
     * @return int|null
     */
    public function getExternalCustomerId()
    {
        return $this->container['external_customer_id'];
    }

    /**
     * Sets external_customer_id
     *
     * @param int|null $external_customer_id ID/Number of the customer in the source system (e.g. an ERP System)
     *
     * @return self
     */
    public function setExternalCustomerId($external_customer_id)
    {
        if (is_null($external_customer_id)) {
            throw new \InvalidArgumentException('non-nullable external_customer_id cannot be null');
        }
        $this->container['external_customer_id'] = $external_customer_id;

        return $this;
    }

    /**
     * Gets external_customer_external_id
     *
     * @return string|null
     */
    public function getExternalCustomerExternalId()
    {
        return $this->container['external_customer_external_id'];
    }

    /**
     * Sets external_customer_external_id
     *
     * @param string|null $external_customer_external_id ID/Number of the customer in a secondary source system (e.g. the shop)
     *
     * @return self
     */
    public function setExternalCustomerExternalId($external_customer_external_id)
    {
        if (is_null($external_customer_external_id)) {
            array_push($this->openAPINullablesSetToNull, 'external_customer_external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_customer_external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($external_customer_external_id) && (mb_strlen($external_customer_external_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $external_customer_external_id when calling Customer., must be smaller than or equal to 64.');
        }

        $this->container['external_customer_external_id'] = $external_customer_external_id;

        return $this;
    }

    /**
     * Gets external_order_type
     *
     * @return string|null
     */
    public function getExternalOrderType()
    {
        return $this->container['external_order_type'];
    }

    /**
     * Sets external_order_type
     *
     * @param string|null $external_order_type external_order_type
     *
     * @return self
     */
    public function setExternalOrderType($external_order_type)
    {
        if (is_null($external_order_type)) {
            throw new \InvalidArgumentException('non-nullable external_order_type cannot be null');
        }
        if ((mb_strlen($external_order_type) > 20)) {
            throw new \InvalidArgumentException('invalid length for $external_order_type when calling Customer., must be smaller than or equal to 20.');
        }

        $this->container['external_order_type'] = $external_order_type;

        return $this;
    }

    /**
     * Gets external_order_account_id
     *
     * @return int|null
     */
    public function getExternalOrderAccountId()
    {
        return $this->container['external_order_account_id'];
    }

    /**
     * Sets external_order_account_id
     *
     * @param int|null $external_order_account_id external_order_account_id
     *
     * @return self
     */
    public function setExternalOrderAccountId($external_order_account_id)
    {
        if (is_null($external_order_account_id)) {
            throw new \InvalidArgumentException('non-nullable external_order_account_id cannot be null');
        }
        $this->container['external_order_account_id'] = $external_order_account_id;

        return $this;
    }

    /**
     * Gets external_order_sub_account_id
     *
     * @return string|null
     */
    public function getExternalOrderSubAccountId()
    {
        return $this->container['external_order_sub_account_id'];
    }

    /**
     * Sets external_order_sub_account_id
     *
     * @param string|null $external_order_sub_account_id external_order_sub_account_id
     *
     * @return self
     */
    public function setExternalOrderSubAccountId($external_order_sub_account_id)
    {
        if (is_null($external_order_sub_account_id)) {
            throw new \InvalidArgumentException('non-nullable external_order_sub_account_id cannot be null');
        }
        if ((mb_strlen($external_order_sub_account_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $external_order_sub_account_id when calling Customer., must be smaller than or equal to 64.');
        }

        $this->container['external_order_sub_account_id'] = $external_order_sub_account_id;

        return $this;
    }

    /**
     * Gets marketplace
     *
     * @return string|null
     */
    public function getMarketplace()
    {
        return $this->container['marketplace'];
    }

    /**
     * Sets marketplace
     *
     * @param string|null $marketplace Marketplace of the customer.
     *
     * @return self
     */
    public function setMarketplace($marketplace)
    {
        if (is_null($marketplace)) {
            throw new \InvalidArgumentException('non-nullable marketplace cannot be null');
        }
        if ((mb_strlen($marketplace) > 64)) {
            throw new \InvalidArgumentException('invalid length for $marketplace when calling Customer., must be smaller than or equal to 64.');
        }

        $this->container['marketplace'] = $marketplace;

        return $this;
    }

    /**
     * Gets test_user
     *
     * @return bool|null
     */
    public function getTestUser()
    {
        return $this->container['test_user'];
    }

    /**
     * Sets test_user
     *
     * @param bool|null $test_user test_user
     *
     * @return self
     */
    public function setTestUser($test_user)
    {
        if (is_null($test_user)) {
            throw new \InvalidArgumentException('non-nullable test_user cannot be null');
        }
        $this->container['test_user'] = $test_user;

        return $this;
    }

    /**
     * Gets newsletter
     *
     * @return bool|null
     */
    public function getNewsletter()
    {
        return $this->container['newsletter'];
    }

    /**
     * Sets newsletter
     *
     * @param bool|null $newsletter newsletter
     *
     * @return self
     */
    public function setNewsletter($newsletter)
    {
        if (is_null($newsletter)) {
            throw new \InvalidArgumentException('non-nullable newsletter cannot be null');
        }
        $this->container['newsletter'] = $newsletter;

        return $this;
    }

    /**
     * Gets segment
     *
     * @return string|null
     */
    public function getSegment()
    {
        return $this->container['segment'];
    }

    /**
     * Sets segment
     *
     * @param string|null $segment Segment of the customer. Read-only, changes via the API will have no effect. Will be required in Q1 2026.
     *
     * @return self
     */
    public function setSegment($segment)
    {
        if (is_null($segment)) {
            throw new \InvalidArgumentException('non-nullable segment cannot be null');
        }
        $this->container['segment'] = $segment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


