<?php
/**
 * Product
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.10.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tid\CustomaPHP\Model;

use \ArrayAccess;
use \Tid\CustomaPHP\ObjectSerializer;

/**
 * Product Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Product implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Product';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'creation_date' => '\DateTime',
        'modification_date' => '\DateTime',
        'id' => 'string',
        'parent' => 'string',
        'number' => 'string',
        'ean' => 'string',
        'name' => 'string',
        'manufacturer' => 'string',
        'vendor' => 'string',
        'short_description' => 'string',
        'long_description' => 'string',
        'image_source' => 'string',
        'status' => 'bool',
        'tax_class' => 'string',
        'stock' => 'int',
        'additional_fields' => '\Tid\CustomaPHP\Model\AdditionalField[]',
        'purchase_price' => '\Tid\CustomaPHP\Model\Price',
        'sales_price' => '\Tid\CustomaPHP\Model\Price',
        'recommended_retail_price' => '\Tid\CustomaPHP\Model\Price'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'creation_date' => 'date-time',
        'modification_date' => 'date-time',
        'id' => null,
        'parent' => null,
        'number' => null,
        'ean' => null,
        'name' => null,
        'manufacturer' => null,
        'vendor' => null,
        'short_description' => null,
        'long_description' => null,
        'image_source' => 'uri',
        'status' => null,
        'tax_class' => null,
        'stock' => null,
        'additional_fields' => null,
        'purchase_price' => null,
        'sales_price' => null,
        'recommended_retail_price' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'creation_date' => false,
        'modification_date' => false,
        'id' => false,
        'parent' => true,
        'number' => false,
        'ean' => false,
        'name' => false,
        'manufacturer' => false,
        'vendor' => false,
        'short_description' => false,
        'long_description' => false,
        'image_source' => false,
        'status' => false,
        'tax_class' => false,
        'stock' => false,
        'additional_fields' => false,
        'purchase_price' => false,
        'sales_price' => false,
        'recommended_retail_price' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'creation_date' => 'CreationDate',
        'modification_date' => 'ModificationDate',
        'id' => 'ID',
        'parent' => 'Parent',
        'number' => 'Number',
        'ean' => 'EAN',
        'name' => 'Name',
        'manufacturer' => 'Manufacturer',
        'vendor' => 'Vendor',
        'short_description' => 'ShortDescription',
        'long_description' => 'LongDescription',
        'image_source' => 'ImageSource',
        'status' => 'Status',
        'tax_class' => 'TaxClass',
        'stock' => 'Stock',
        'additional_fields' => 'AdditionalFields',
        'purchase_price' => 'PurchasePrice',
        'sales_price' => 'SalesPrice',
        'recommended_retail_price' => 'RecommendedRetailPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'creation_date' => 'setCreationDate',
        'modification_date' => 'setModificationDate',
        'id' => 'setId',
        'parent' => 'setParent',
        'number' => 'setNumber',
        'ean' => 'setEan',
        'name' => 'setName',
        'manufacturer' => 'setManufacturer',
        'vendor' => 'setVendor',
        'short_description' => 'setShortDescription',
        'long_description' => 'setLongDescription',
        'image_source' => 'setImageSource',
        'status' => 'setStatus',
        'tax_class' => 'setTaxClass',
        'stock' => 'setStock',
        'additional_fields' => 'setAdditionalFields',
        'purchase_price' => 'setPurchasePrice',
        'sales_price' => 'setSalesPrice',
        'recommended_retail_price' => 'setRecommendedRetailPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'creation_date' => 'getCreationDate',
        'modification_date' => 'getModificationDate',
        'id' => 'getId',
        'parent' => 'getParent',
        'number' => 'getNumber',
        'ean' => 'getEan',
        'name' => 'getName',
        'manufacturer' => 'getManufacturer',
        'vendor' => 'getVendor',
        'short_description' => 'getShortDescription',
        'long_description' => 'getLongDescription',
        'image_source' => 'getImageSource',
        'status' => 'getStatus',
        'tax_class' => 'getTaxClass',
        'stock' => 'getStock',
        'additional_fields' => 'getAdditionalFields',
        'purchase_price' => 'getPurchasePrice',
        'sales_price' => 'getSalesPrice',
        'recommended_retail_price' => 'getRecommendedRetailPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TAX_CLASS_NORMAL = 'Normal';
    public const TAX_CLASS_REDUCED = 'Reduced';
    public const TAX_CLASS_HIGHLY_REDUCED = 'HighlyReduced';
    public const TAX_CLASS_NONE = 'None';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTaxClassAllowableValues()
    {
        return [
            self::TAX_CLASS_NORMAL,
            self::TAX_CLASS_REDUCED,
            self::TAX_CLASS_HIGHLY_REDUCED,
            self::TAX_CLASS_NONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('modification_date', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('parent', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('ean', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('manufacturer', $data ?? [], null);
        $this->setIfExists('vendor', $data ?? [], null);
        $this->setIfExists('short_description', $data ?? [], null);
        $this->setIfExists('long_description', $data ?? [], null);
        $this->setIfExists('image_source', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('tax_class', $data ?? [], null);
        $this->setIfExists('stock', $data ?? [], null);
        $this->setIfExists('additional_fields', $data ?? [], null);
        $this->setIfExists('purchase_price', $data ?? [], null);
        $this->setIfExists('sales_price', $data ?? [], null);
        $this->setIfExists('recommended_retail_price', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['number']) && (mb_strlen($this->container['number']) > 255)) {
            $invalidProperties[] = "invalid value for 'number', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['ean']) && (mb_strlen($this->container['ean']) > 32)) {
            $invalidProperties[] = "invalid value for 'ean', the character length must be smaller than or equal to 32.";
        }

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['manufacturer']) && (mb_strlen($this->container['manufacturer']) > 64)) {
            $invalidProperties[] = "invalid value for 'manufacturer', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['vendor']) && (mb_strlen($this->container['vendor']) > 128)) {
            $invalidProperties[] = "invalid value for 'vendor', the character length must be smaller than or equal to 128.";
        }

        $allowedValues = $this->getTaxClassAllowableValues();
        if (!is_null($this->container['tax_class']) && !in_array($this->container['tax_class'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tax_class', must be one of '%s'",
                $this->container['tax_class'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets creation_date
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime|null $creation_date Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setCreationDate($creation_date)
    {
        if (is_null($creation_date)) {
            throw new \InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets modification_date
     *
     * @return \DateTime|null
     */
    public function getModificationDate()
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     *
     * @param \DateTime|null $modification_date Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setModificationDate($modification_date)
    {
        if (is_null($modification_date)) {
            throw new \InvalidArgumentException('non-nullable modification_date cannot be null');
        }
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID of the product. Set internally by Customa, any given value is ignored.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets parent
     *
     * @return string|null
     */
    public function getParent()
    {
        return $this->container['parent'];
    }

    /**
     * Sets parent
     *
     * @param string|null $parent ID of the parent product. The parent must be standalone and not have a parent itself.
     *
     * @return self
     */
    public function setParent($parent)
    {
        if (is_null($parent)) {
            array_push($this->openAPINullablesSetToNull, 'parent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent'] = $parent;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string|null $number Product number, MUST be unique.
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        if ((mb_strlen($number) > 255)) {
            throw new \InvalidArgumentException('invalid length for $number when calling Product., must be smaller than or equal to 255.');
        }

        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string|null
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string|null $ean EAN of the product.
     *
     * @return self
     */
    public function setEan($ean)
    {
        if (is_null($ean)) {
            throw new \InvalidArgumentException('non-nullable ean cannot be null');
        }
        if ((mb_strlen($ean) > 32)) {
            throw new \InvalidArgumentException('invalid length for $ean when calling Product., must be smaller than or equal to 32.');
        }

        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of the product.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Product., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string|null
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string|null $manufacturer Manufacturer of the product.
     *
     * @return self
     */
    public function setManufacturer($manufacturer)
    {
        if (is_null($manufacturer)) {
            throw new \InvalidArgumentException('non-nullable manufacturer cannot be null');
        }
        if ((mb_strlen($manufacturer) > 64)) {
            throw new \InvalidArgumentException('invalid length for $manufacturer when calling Product., must be smaller than or equal to 64.');
        }

        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets vendor
     *
     * @return string|null
     */
    public function getVendor()
    {
        return $this->container['vendor'];
    }

    /**
     * Sets vendor
     *
     * @param string|null $vendor Vendor of the product.
     *
     * @return self
     */
    public function setVendor($vendor)
    {
        if (is_null($vendor)) {
            throw new \InvalidArgumentException('non-nullable vendor cannot be null');
        }
        if ((mb_strlen($vendor) > 128)) {
            throw new \InvalidArgumentException('invalid length for $vendor when calling Product., must be smaller than or equal to 128.');
        }

        $this->container['vendor'] = $vendor;

        return $this;
    }

    /**
     * Gets short_description
     *
     * @return string|null
     */
    public function getShortDescription()
    {
        return $this->container['short_description'];
    }

    /**
     * Sets short_description
     *
     * @param string|null $short_description Short description of the product.
     *
     * @return self
     */
    public function setShortDescription($short_description)
    {
        if (is_null($short_description)) {
            throw new \InvalidArgumentException('non-nullable short_description cannot be null');
        }
        $this->container['short_description'] = $short_description;

        return $this;
    }

    /**
     * Gets long_description
     *
     * @return string|null
     */
    public function getLongDescription()
    {
        return $this->container['long_description'];
    }

    /**
     * Sets long_description
     *
     * @param string|null $long_description Long description of the product.
     *
     * @return self
     */
    public function setLongDescription($long_description)
    {
        if (is_null($long_description)) {
            throw new \InvalidArgumentException('non-nullable long_description cannot be null');
        }
        $this->container['long_description'] = $long_description;

        return $this;
    }

    /**
     * Gets image_source
     *
     * @return string|null
     */
    public function getImageSource()
    {
        return $this->container['image_source'];
    }

    /**
     * Sets image_source
     *
     * @param string|null $image_source Source URI of the product image.
     *
     * @return self
     */
    public function setImageSource($image_source)
    {
        if (is_null($image_source)) {
            throw new \InvalidArgumentException('non-nullable image_source cannot be null');
        }
        $this->container['image_source'] = $image_source;

        return $this;
    }

    /**
     * Gets status
     *
     * @return bool|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param bool|null $status Whether the product is active or inactive.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tax_class
     *
     * @return string|null
     */
    public function getTaxClass()
    {
        return $this->container['tax_class'];
    }

    /**
     * Sets tax_class
     *
     * @param string|null $tax_class Tax class of the product. For example, in Germany, 19% VAT would be 'Normal' while 7% VAT would be 'Reduced'.
     *
     * @return self
     */
    public function setTaxClass($tax_class)
    {
        if (is_null($tax_class)) {
            throw new \InvalidArgumentException('non-nullable tax_class cannot be null');
        }
        $allowedValues = $this->getTaxClassAllowableValues();
        if (!in_array($tax_class, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tax_class', must be one of '%s'",
                    $tax_class,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tax_class'] = $tax_class;

        return $this;
    }

    /**
     * Gets stock
     *
     * @return int|null
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     *
     * @param int|null $stock Stock of the product.
     *
     * @return self
     */
    public function setStock($stock)
    {
        if (is_null($stock)) {
            throw new \InvalidArgumentException('non-nullable stock cannot be null');
        }
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets additional_fields
     *
     * @return \Tid\CustomaPHP\Model\AdditionalField[]|null
     */
    public function getAdditionalFields()
    {
        return $this->container['additional_fields'];
    }

    /**
     * Sets additional_fields
     *
     * @param \Tid\CustomaPHP\Model\AdditionalField[]|null $additional_fields Additional field data for the product.
     *
     * @return self
     */
    public function setAdditionalFields($additional_fields)
    {
        if (is_null($additional_fields)) {
            throw new \InvalidArgumentException('non-nullable additional_fields cannot be null');
        }
        $this->container['additional_fields'] = $additional_fields;

        return $this;
    }

    /**
     * Gets purchase_price
     *
     * @return \Tid\CustomaPHP\Model\Price|null
     */
    public function getPurchasePrice()
    {
        return $this->container['purchase_price'];
    }

    /**
     * Sets purchase_price
     *
     * @param \Tid\CustomaPHP\Model\Price|null $purchase_price purchase_price
     *
     * @return self
     */
    public function setPurchasePrice($purchase_price)
    {
        if (is_null($purchase_price)) {
            throw new \InvalidArgumentException('non-nullable purchase_price cannot be null');
        }
        $this->container['purchase_price'] = $purchase_price;

        return $this;
    }

    /**
     * Gets sales_price
     *
     * @return \Tid\CustomaPHP\Model\Price|null
     */
    public function getSalesPrice()
    {
        return $this->container['sales_price'];
    }

    /**
     * Sets sales_price
     *
     * @param \Tid\CustomaPHP\Model\Price|null $sales_price sales_price
     *
     * @return self
     */
    public function setSalesPrice($sales_price)
    {
        if (is_null($sales_price)) {
            throw new \InvalidArgumentException('non-nullable sales_price cannot be null');
        }
        $this->container['sales_price'] = $sales_price;

        return $this;
    }

    /**
     * Gets recommended_retail_price
     *
     * @return \Tid\CustomaPHP\Model\Price|null
     */
    public function getRecommendedRetailPrice()
    {
        return $this->container['recommended_retail_price'];
    }

    /**
     * Sets recommended_retail_price
     *
     * @param \Tid\CustomaPHP\Model\Price|null $recommended_retail_price recommended_retail_price
     *
     * @return self
     */
    public function setRecommendedRetailPrice($recommended_retail_price)
    {
        if (is_null($recommended_retail_price)) {
            throw new \InvalidArgumentException('non-nullable recommended_retail_price cannot be null');
        }
        $this->container['recommended_retail_price'] = $recommended_retail_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


