<?php
/**
 * StatsReceiptType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tid\CustomaPHP\Model;

use \ArrayAccess;
use \Tid\CustomaPHP\ObjectSerializer;

/**
 * StatsReceiptType Class Doc Comment
 *
 * @category Class
 * @description Statistics for a specific receipt type.
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StatsReceiptType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StatsReceiptType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'receipt_type' => 'string',
        'receipt_count' => 'int',
        'customer_count' => 'int',
        'revenue' => '\Tid\CustomaPHP\Model\Price',
        'cost_of_goods_sold' => '\Tid\CustomaPHP\Model\Price'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'receipt_type' => null,
        'receipt_count' => null,
        'customer_count' => null,
        'revenue' => null,
        'cost_of_goods_sold' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'receipt_type' => false,
        'receipt_count' => false,
        'customer_count' => false,
        'revenue' => false,
        'cost_of_goods_sold' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'receipt_type' => 'ReceiptType',
        'receipt_count' => 'ReceiptCount',
        'customer_count' => 'CustomerCount',
        'revenue' => 'Revenue',
        'cost_of_goods_sold' => 'CostOfGoodsSold'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'receipt_type' => 'setReceiptType',
        'receipt_count' => 'setReceiptCount',
        'customer_count' => 'setCustomerCount',
        'revenue' => 'setRevenue',
        'cost_of_goods_sold' => 'setCostOfGoodsSold'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'receipt_type' => 'getReceiptType',
        'receipt_count' => 'getReceiptCount',
        'customer_count' => 'getCustomerCount',
        'revenue' => 'getRevenue',
        'cost_of_goods_sold' => 'getCostOfGoodsSold'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('receipt_type', $data ?? [], null);
        $this->setIfExists('receipt_count', $data ?? [], null);
        $this->setIfExists('customer_count', $data ?? [], null);
        $this->setIfExists('revenue', $data ?? [], null);
        $this->setIfExists('cost_of_goods_sold', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['receipt_type'] === null) {
            $invalidProperties[] = "'receipt_type' can't be null";
        }
        if ($this->container['receipt_count'] === null) {
            $invalidProperties[] = "'receipt_count' can't be null";
        }
        if ($this->container['customer_count'] === null) {
            $invalidProperties[] = "'customer_count' can't be null";
        }
        if ($this->container['revenue'] === null) {
            $invalidProperties[] = "'revenue' can't be null";
        }
        if ($this->container['cost_of_goods_sold'] === null) {
            $invalidProperties[] = "'cost_of_goods_sold' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets receipt_type
     *
     * @return string
     */
    public function getReceiptType()
    {
        return $this->container['receipt_type'];
    }

    /**
     * Sets receipt_type
     *
     * @param string $receipt_type The type of the receipt.
     *
     * @return self
     */
    public function setReceiptType($receipt_type)
    {
        if (is_null($receipt_type)) {
            throw new \InvalidArgumentException('non-nullable receipt_type cannot be null');
        }
        $this->container['receipt_type'] = $receipt_type;

        return $this;
    }

    /**
     * Gets receipt_count
     *
     * @return int
     */
    public function getReceiptCount()
    {
        return $this->container['receipt_count'];
    }

    /**
     * Sets receipt_count
     *
     * @param int $receipt_count The number of receipts of the specified type.
     *
     * @return self
     */
    public function setReceiptCount($receipt_count)
    {
        if (is_null($receipt_count)) {
            throw new \InvalidArgumentException('non-nullable receipt_count cannot be null');
        }
        $this->container['receipt_count'] = $receipt_count;

        return $this;
    }

    /**
     * Gets customer_count
     *
     * @return int
     */
    public function getCustomerCount()
    {
        return $this->container['customer_count'];
    }

    /**
     * Sets customer_count
     *
     * @param int $customer_count The number of customers who had at least one receipt of the specified type. This number may be lower than the `ReceiptCount` if some customers had multiple receipts of the specified type.
     *
     * @return self
     */
    public function setCustomerCount($customer_count)
    {
        if (is_null($customer_count)) {
            throw new \InvalidArgumentException('non-nullable customer_count cannot be null');
        }
        $this->container['customer_count'] = $customer_count;

        return $this;
    }

    /**
     * Gets revenue
     *
     * @return \Tid\CustomaPHP\Model\Price
     */
    public function getRevenue()
    {
        return $this->container['revenue'];
    }

    /**
     * Sets revenue
     *
     * @param \Tid\CustomaPHP\Model\Price $revenue revenue
     *
     * @return self
     */
    public function setRevenue($revenue)
    {
        if (is_null($revenue)) {
            throw new \InvalidArgumentException('non-nullable revenue cannot be null');
        }
        $this->container['revenue'] = $revenue;

        return $this;
    }

    /**
     * Gets cost_of_goods_sold
     *
     * @return \Tid\CustomaPHP\Model\Price
     */
    public function getCostOfGoodsSold()
    {
        return $this->container['cost_of_goods_sold'];
    }

    /**
     * Sets cost_of_goods_sold
     *
     * @param \Tid\CustomaPHP\Model\Price $cost_of_goods_sold cost_of_goods_sold
     *
     * @return self
     */
    public function setCostOfGoodsSold($cost_of_goods_sold)
    {
        if (is_null($cost_of_goods_sold)) {
            throw new \InvalidArgumentException('non-nullable cost_of_goods_sold cannot be null');
        }
        $this->container['cost_of_goods_sold'] = $cost_of_goods_sold;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


