<?php
/**
 * GlobalSettingValueTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.10.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Tid\CustomaPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GlobalSettingValueTest Class Doc Comment
 *
 * @category    Class
 * @description The global value of the setting, which applies when no marketplace-specific value is set and a project fallback is used. This value can be of type string, integer, float, or boolean, depending on the specific setting being represented.
 * @package     Tid\CustomaPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GlobalSettingValueTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GlobalSettingValue"
     */
    public function testGlobalSettingValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
