<?php
/**
 * SegmentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.13.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Tid\CustomaPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SegmentTest Class Doc Comment
 *
 * @category    Class
 * @description A single customer segment generated from the segment definition.
 * @package     Tid\CustomaPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SegmentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Segment"
     */
    public function testSegment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monetary"
     */
    public function testPropertyMonetary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_lifetime_value"
     */
    public function testPropertyCustomerLifetimeValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recency"
     */
    public function testPropertyRecency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
