<?php
/**
 * CustomerApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.10.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tid\CustomaPHP\Test\Api;

use \Tid\CustomaPHP\Configuration;
use \Tid\CustomaPHP\ApiException;
use \Tid\CustomaPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customerDeleteV3
     *
     * Deletes a customer with the given ID..
     *
     */
    public function testCustomerDeleteV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeleteV4
     *
     * Deletes a customer by their ID..
     *
     */
    public function testCustomerDeleteV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetV3
     *
     * Retrieves a customer by their ID..
     *
     */
    public function testCustomerGetV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetV4
     *
     * Retrieves a customer by their ID..
     *
     */
    public function testCustomerGetV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPatchV3
     *
     * Updates a customer with the given ID partially..
     *
     */
    public function testCustomerPatchV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPostV3
     *
     * Creates a new Customer..
     *
     */
    public function testCustomerPostV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPostV4
     *
     * Creates a new customer..
     *
     */
    public function testCustomerPostV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPutV3
     *
     * Overwrites a customer with the given ID..
     *
     */
    public function testCustomerPutV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPutV4
     *
     * Overwrites an existing customer with the given ID..
     *
     */
    public function testCustomerPutV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSearchV3
     *
     * Searches for customers by the given filters..
     *
     */
    public function testCustomerSearchV3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSearchV4
     *
     * Searches for customers by the given filters..
     *
     */
    public function testCustomerSearchV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
