<?php
/**
 * CustomerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tid\CustomaPHP\Test\Api;

use \Tid\CustomaPHP\Configuration;
use \Tid\CustomaPHP\ApiException;
use \Tid\CustomaPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customerDelete
     *
     * Deletes a customer with the given ID..
     *
     */
    public function testCustomerDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGet
     *
     * Retrieves a customer by their ID..
     *
     */
    public function testCustomerGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPatch
     *
     * Updates a customer with the given ID partially..
     *
     */
    public function testCustomerPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPost
     *
     * Creates a new Customer..
     *
     */
    public function testCustomerPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerPut
     *
     * Overwrites a customer with the given ID..
     *
     */
    public function testCustomerPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSearch
     *
     * Searches for customers by the given filters..
     *
     */
    public function testCustomerSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
