<?php
/**
 * CustomergroupApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tid\CustomaPHP\Test\Api;

use \Tid\CustomaPHP\Configuration;
use \Tid\CustomaPHP\ApiException;
use \Tid\CustomaPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomergroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomergroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customergroupDeleteV4
     *
     * Deletes a customer group by its ID..
     *
     */
    public function testCustomergroupDeleteV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupFieldsV4
     *
     * Returns a list of fields and allowed filters for customer group search..
     *
     */
    public function testCustomergroupFieldsV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupGetV4
     *
     * Retrieves a customer group by its ID..
     *
     */
    public function testCustomergroupGetV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupPatchV4
     *
     * Partially updates an existing customer group with the given ID..
     *
     */
    public function testCustomergroupPatchV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupPostV4
     *
     * Creates a new customer group..
     *
     */
    public function testCustomergroupPostV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupPutV4
     *
     * Overwrites an existing customer group with the given ID..
     *
     */
    public function testCustomergroupPutV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customergroupSearchV4
     *
     * Searches for customer groups by the given filters..
     *
     */
    public function testCustomergroupSearchV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
