<?php
/**
 * ProductApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tid\CustomaPHP\Test\Api;

use \Tid\CustomaPHP\Configuration;
use \Tid\CustomaPHP\ApiException;
use \Tid\CustomaPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productDelete
     *
     * Deletes a product by its ID..
     *
     */
    public function testProductDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productGet
     *
     * Retrieves a product by its ID..
     *
     */
    public function testProductGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPatch
     *
     * Updates a product partially by its ID..
     *
     */
    public function testProductPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPost
     *
     * Creates a new Product..
     *
     */
    public function testProductPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productPut
     *
     * Overwrites an existing product with the given ID..
     *
     */
    public function testProductPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productSearch
     *
     * Searches for products by the given filters..
     *
     */
    public function testProductSearch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
