<?php
/**
 * TrafficApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Customa
 *
 * E-Commerce BI & CRM Tool
 *
 * The version of the OpenAPI document: 3.13.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tid\CustomaPHP\Test\Api;

use \Tid\CustomaPHP\Configuration;
use \Tid\CustomaPHP\ApiException;
use \Tid\CustomaPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TrafficApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tid\CustomaPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrafficApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for trafficDataV4
     *
     * Returns traffic data for the given project and filters..
     *
     */
    public function testTrafficDataV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for trafficFiltersV4
     *
     * Returns available filter options for the traffic analyzer..
     *
     */
    public function testTrafficFiltersV4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
